version: "3.9"

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map Vite dev server port
    volumes:
      - .:/app # Mount current directory to the container for live updates
      - /app/node_modules # Ignore host's node_modules
    stdin_open: true
    tty: true
